events:
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  intersection_go_explicit:
    topic: "coordinator_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  intersection_done:  ## closed loop new
    topic: "intersection_navigation_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True
  vehicle_caused_stop:
    topic: "vehicle_detection_node/vehicle_caused_stop"
    msg_type: "BoolStamped"
    trigger: True
  pedestrian_caused_stop:
    topic: "object_detection_node/pedestrian_caused_stop"
    msg_type: "BoolStamped"
    trigger: True

  vehicle_cleared:
    topic: "vehicle_detection_node/vehicle_caused_stop"
    msg_type: "BoolStamped"
    trigger: False
  pedestrian_cleared:
    topic: "object_detection_node/pedestrian_caused_stop"
    msg_type: "BoolStamped"
    trigger: False

  vehicle_timeout:
    topic: "vehicle_detection_node/timeout"
    msg_type: "BoolStamped"
    trigger: True
  pedestrian_timeout:
    topic: "object_detection_node/timeout"
    msg_type: "BoolStamped"
    trigger: True

  finish_switch_lane:
    topic: "lane_controller_node/finish_switch_lane"
    msg_type: "BoolStamped"
    trigger: True


gates:
  intersection_go:
    gate_type: OR
    inputs:
      - intersection_go_implicit
      - intersection_go_explicit
    output_topic: "~intersection_go"

  obstacle_caused_stop:
    gate_type: OR
    inputs:
      - vehicle_caused_stop
      - pedestrian_caused_stop
    output_topic: "~obstacle_caused_stop"

  obstacle_cleared:
    gate_type: AND
    inputs:
      - vehicle_cleared
      - pedestrian_cleared
    output_topic: "~obstacle_cleared"

  obstacle_timeout:
    gate_type: OR
    inputs:
      - vehicle_timeout
      - pedestrian_timeout
    output_topic: "~obstacle_timeout"
