# Initial state of the FSM

initial_state: "NORMAL_JOYSTICK_CONTROL"

events: # Maps from subscribing topic to signal ids
  joystick_override_on:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_off:
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  intersection_go:
    topic: "coordinator_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  intersection_done: ## closed loop new
    topic: "intersection_navigation_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True
  obstacle_caused_stop:
    topic: "logic_gate_node/obstacle_caused_stop"
    msg_type: "BoolStamped"
    trigger: True
  obstacle_cleared:
    topic: "logic_gate_node/obstacle_caused_stop"
    msg_type: "BoolStamped"
    trigger: False
  finish_switch_lane:
    topic: "lane_controller_node/finish_switch_lane"
    msg_type: "BoolStamped"
    trigger: True
  obstacle_timeout:
    topic: "logic_gate_node/obstacle_timeout"
    msg_type: "BoolStamped"
    trigger: True

# Define nodes
nodes:
  decoder_node: "decoder_node/switch"
  anti_instagram: "anti_instagram_node/switch"
  led_emitter_node: "led_emitter_node/switch"
  led_detector_node: "led_detector_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  framerate_high: "camera_node/framerate_high_switch"
  # extras added

  unicorn_intersection_node: "unicorn_intersection_node/switch" #NOTE a.k.a. semi closed loop intersection navigation
  lane_controller_node: "lane_controller_node/switch"
  vehicle_filter_node: "vehicle_filter_node/switch"
  # vehicle_avoidance_control_node: "vehicle_avoidance_control_node/switch"
  vehicle_detection_node: "vehicle_detection_node/switch"

# Define state transitions

global_transitions:
  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"

states:
  NORMAL_JOYSTICK_CONTROL:
    transitions:
      joystick_override_off: "LANE_FOLLOWING"
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
      - framerate_high
      - decoder_node
    lights: ["joystick"]
    current_status: "implemented"

  LANE_FOLLOWING:
    transitions:
      obstacle_caused_stop: "OBSTACLE_STOP"
      at_stop_line: "INTERSECTION_COORDINATION"
    active_nodes:
      - anti_instagram
      - decoder_node
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
      - stop_line_filter_node
      - vehicle_filter_node
      - vehicle_detection_node
      - vehicle_avoidance_control_node
    lights: ["lane_following"]
    current_status: "in_progress"

  INTERSECTION_COORDINATION:
    transitions:
      intersection_go: "INTERSECTION_CONTROL"
    active_nodes:
      - apriltag_node #NOTE
      - lane_filter_node
      - lane_controller_node
      - line_detector_node # NOTE possibly
      - decoder_node
      - framerate_high
      - led_emitter_node
      - led_detector_node
      - coordinator_node
      - unicorn_intersection_node
    lights: ["coordination"]
    current_status: "in_progress"

  INTERSECTION_CONTROL:
    transitions:
      intersection_done: "LANE_FOLLOWING"
    active_nodes:
      - decoder_node
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
      - unicorn_intersection_node
    current_status: "in_progress"

  OBSTACLE_STOP:
    transitions:
      obstacle_cleared: "LANE_FOLLOWING"
      obstacle_timeout: "SWITCH_LANE_LEFT"
    active_nodes:
      - anti_instagram
      - decoder_node
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
      - vehicle_filter_node
      - vehicle_detection_node
      - vehicle_avoidance_control_node
    lights: ["coordination"]
    current_status: "in_progress"

  SWITCH_LANE_LEFT:
    transitions:
      finish_switch_lane: "OBSTACLE_AVOIDANCE"
    active_nodes:
      - anti_instagram
      - decoder_node
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
      - vehicle_filter_node
      - vehicle_detection_node
      - vehicle_avoidance_control_node
    lights: [ "coordination" ]
    current_status: "in_progress"

  OBSTACLE_AVOIDANCE:
    transitions:
      obstacle_timeout: "SWITCH_LANE_RIGHT"
    active_nodes:
      - anti_instagram
      - decoder_node
      - line_detector_node
      - lane_filter_node
      - lane_controller_node
    lights: [ "coordination" ]
    current_status: "in_progress"

    SWITCH_LANE_RIGHT:
      transitions:
        finish_switch_lane: "LANE_FOLLOWING"
      active_nodes:
        - anti_instagram
        - decoder_node
        - line_detector_node
        - lane_filter_node
        - lane_controller_node
      lights: [ "coordination" ]
      current_status: "in_progress"

#
#global_transitions:
#  joystick_override_on: "NORMAL_JOYSTICK_CONTROL"
#
#states:
#  NORMAL_JOYSTICK_CONTROL:
#    transitions:
#      joystick_override_off: "LANE_FOLLOWING"
#    active_nodes:
#      - lane_filter_node
#      - line_detector_node
#      - stop_line_filter_node
#      - framerate_high
#      - decoder_node
#    lights: ["joystick"]
#    current_status: "implemented"
#
#  LANE_FOLLOWING:
#    transitions:
#      at_stop_line: "INTERSECTION_COORDINATION"
#      obstacle_caused_stop: "OBSTACLE_STOP"
#    active_nodes:
#      - anti_instagram
#      - decoder_node
#      - line_detector_node
#      - lane_filter_node
#      - lane_controller_node
#      - stop_line_filter_node
#      - vehicle_filter_node
#      - vehicle_detection_node
#      # - vehicle_avoidance_control_node
#    lights: ["lane_following"]
#    current_status: "in_progress"
#
#  INTERSECTION_COORDINATION:
#    transitions:
#      intersection_go: "INTERSECTION_CONTROL"
#    active_nodes:
#      # - apriltag_node #NOTE
#      - lane_filter_node
#      - lane_controller_node
#      - line_detector_node # NOTE possibly
#      - decoder_node
#      - framerate_high
#      - led_emitter_node
#      - led_detector_node
#      - unicorn_intersection_node
#      # - traffic_light_node ## Need to implement traffic control here
#    lights: ["coordination"]
#    current_status: "in_progress"
#
#  INTERSECTION_CONTROL:
#    transitions:
#      intersection_done: "LANE_FOLLOWING"
#    active_nodes:
#      - decoder_node
#      - line_detector_node
#      - lane_filter_node
#      - lane_controller_node
#      - stop_line_filter_node
#      - unicorn_intersection_node
#    current_status: "in_progress"
#
#  # OBSTACLE_ALERT:
#  #   transitions:
#  #     at_stop_line: "INTERSECTION_COORDINATION"
#  #     obstacle_caused_stop: "OBSTACLE_STOP"
#  #     obstacle_cleared: "LANE_FOLLOWING"
#
#  #   active_nodes:
#  #     - anti_instagram
#  #     - decoder_node
#  #     - line_detector_node
#  #     - lane_filter_node
#  #     - lane_controller_node
#  #     - stop_line_filter_node
#  #     - vehicle_filter_node
#  #     - vehicle_detection_node
#  #     - vehicle_avoidance_control_node
#  #   lights: ["coordination"]
#  #   current_status: "in_progress"
#
#  OBSTACLE_STOP:
#    transitions:
#      obstacle_caused_stop: "OBSTACLE_STOP"
#      obstacle_cleared: "LANE_FOLLOWING"
#
#    active_nodes:
#      - anti_instagram
#      - decoder_node
#      - line_detector_node
#      - lane_filter_node
#      - lane_controller_node
#      - stop_line_filter_node
#      - vehicle_filter_node
#      - vehicle_detection_node
#      # - vehicle_avoidance_control_node
#    lights: ["coordination"]
#    current_status: "in_progress"
